### ISSUE TITLE
Support GlobaLeaks behind firewall that block outgoing connection to check.torproject.org

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/globaleaks-whistleblowing-software#2500]
**Current behavior**
Certain users that install GlobaLeaks behind restrictive firewall, can't have their globaleaks update the list of Tor Exit Addresses because outgoing connection to https://check.torproject.org/exit-addresses are blocked.

This ticket is to fix that problem by introducing GlobaLeaks as a proxy to download this resource.

**Expected behavior**
We've configured on deb.globaleaks.org an nginx proxy resource:
	location /exit-addresses {
		proxy_pass  https://check.torproject.org/exit-addresses;
	}

That make available at address https://deb.globaleaks.org/exit-addresses the resource https://check.torproject.org/exit-addresses .

This ticket is to introduce a download attempt using https://deb.globaleaks.org/exit-addresses rather than https://check.torproject.org/exit-addresses .

**Comment by evilaliv3** [comment]
This is definitely doable and interesting.

Let's put the resource in a specific path /app in order to not mess up with the debian repository.

In the future we may evaluate to use a specific domain apps.globaleaks.org.
This will be surely necessary when we will have multiple repositories like for example as planned for CENTOS/RedHat in: https://github.com/globaleaks/GlobaLeaks/issues/786

**Comment by fpietrosanti** [comment]
Published on curl -v https://deb.globaleaks.org/app/exit-addresses
