### ISSUE TITLE
GUI Bug - Danish language

### ISSUE THREAD

**Issue by wk-gh-user** [globaleaks/globaleaks-whistleblowing-software#2508]
**Current behavior**
Nothing is broken, is more a cosmetic thing. When you want to select danish as language, it shows 'propably' Danish in another written language. I've attached a screenshot.

![danish-lang](https://user-images.githubusercontent.com/46743975/52264117-2efd4f80-2931-11e9-94c2-02593ba3429c.png)

**Expected behavior**
When language dropdown box is clicked, I expect it to show 'Danish' or 'Dansk'

**Steps to reproduce the problem or feature illustration**
Enable danish language in the admin portal, Reload the site and click the language button to select Danish...

**What is the motivation or use case for changing the behavior?**
For danish users or companies who needs it in danish, it would be easier to find the danish language - when it's written as 'Danish' or 'Dansk'.

**GlobaLeaks version:**
3.6.x+

**Browser:**
Firefox, Chrome, Internet Explorer

**Server Operating System and Version (if applicable):**
Ubuntu 18.04.1 LTS

**Client Operating System and Version (if applicable):**
Linux, Windows

**Comment by evilaliv3** [comment]
Dear @mryber,

thank you for notifying us this issue, it will be fixed in the upcoming 3.6.12

I see that the Danish translation is not complete (89%); If you would like to complete it by yourself you could register on Transifex and pass me your nickname or email and I may add you as reviewer for Danish so that you could review the current translations created by volunteers.

**Comment by evilaliv3** [comment]
Great! Let me know!
