### ISSUE TITLE
Visibility of report status changes' motivations

### ISSUE THREAD

**Issue by evariitta** [globaleaks/globaleaks-whistleblowing-software#4201]
### Proposal

We have an issue with transparency of status change motivations. 
 
Recipients were unaware that the motivations they wrote when closing reports would later be visible to whistleblowers. It would be problematic to let whistleblowers see texts that recipients believed were private.

### Motivation and context

We wouldn't have this issue if previously written texts didn’t become retroactively visible after the version 5 update. Would it be possible to work around this somehow?

**Comment by evilaliv3** [comment]
Thank you @evariitta for raising this concern. that is is very valid.

Unfortunately, the problem lies in a contribution that we received to support a national authority that has in fact this usability issue.

The current implementation considers that the motivation should be transparently shown to whistleblowers following the same principles of any information that the platform tracks and this choice is based on the same principles of transparency  and accountability of the entire project.

Unfortunately even if discussing to have found a solution i dont think one exists. I do not see an easy solution since some users may have thought it was public and others private so we can simply flip the visibility.

I suggest we could  just document a query to remove the motivation of the system, so that organizations that may have incorrectly thought this information was private could remove the motivation of all the existing reports or an existing set of reports given that date.  

Lets see what other of the most relevant users of the system thing to find a strategy to mitigate the issue that you are describing.

\cc @larrykind @elbill @giorgiofraschini @javialama @msmannan00 @danielvaknine

**Comment by JaviAlama** [comment]
In our case we are not affected by this problem. Although we initially defined several statuses, we finally used the basic ones of New, Open and Closed. We incorporate other intermediate cases such as ‘Pending Acknowledgement of Receipt’, ‘in Processing’, ‘under Analysis’, etc...

The management of the complaint and the evolution of its processing is managed entirely through the Electronic File Manager. We use the mailbox to communicate with the complainant and we do not motivate the change of status, except at the closing when we incorporate the Resolution of Conclusion of the file.

**Comment by evariitta** [comment]
Thank you. 
A query would be helpful for us.

**Comment by danielvaknine** [comment]
After testing this feature out we agree that it is too unclear and unexplained to the user that the motivation becomes visible to the whistleblower.

We therefore suggest to either
1. Not show the motivation to the whistleblower but only to the recipient(s)
2. Clarify to the recipient that the motivation will be shown to the whistleblower

We suggest option 1 until enough languages have been translated to have an effective option 2.

**Comment by giorgiofraschini** [comment]
i quite agree with @danielvaknine on this. We should make it easier for the recipient to understand that this motivation will be shown to the whistleblower.

**Comment by evilaliv3** [comment]
I agree on your points and i'm in definitely in favour of studying better interfaces but this unfortunately will require time and study to be included in next major released.

At  the moment the best is to properly document this to users when we offer the platform, e.g. creating a documentation section that explicit that every information that is shared on the platform is public to the whistleblower except:
1. reports labels
2. reports private comments

I suggest we should could have a section of the documentation with a table explaining for each type of data (e.g. comments, files, labels, ...) which is the visibility.

**Comment by evilaliv3** [comment]
@danielvaknine @elbill @JaviAlama @larrykind @giorgiofraschini

I think we received a lot of criticism from you and other users about the implementation of the motivations on reports status changes.
I propose to remove completely the possibility to provide a motivation when changing the status the report and delete the motivations in status changes. Anyhow if users want to provide a motivation (public or private) they could use comments.

Do you agree?

**Comment by giorgiofraschini** [comment]
I agree with you @evilaliv3. remove it completely. motivations should be provided through comments.

**Comment by evilaliv3** [comment]
Thank you @danielvaknine 

At the moment we consider it is better to simplify, anyhow recipients will be able to perform private annotations using comments in the "Only recipients" tab.

**Comment by danielvaknine** [comment]
Hello, has this been implemented? And if so, from which system version?
