### ISSUE TITLE
Mandatory voice fields not filled do not block the saving of the report

### ISSUE THREAD

**Issue by maelaborazioni** [globaleaks/globaleaks-whistleblowing-software#4304]
By setting up a questionnaire with a series of questions, all of the "voice" type, all mandatory and all with a minimum length = 1, the questionnaire is still saved even if the fields are not filled in (recorded). 
The error messages in red under the audio recorder icon are shown but the report is saved anyway.

Edit: Found using GL 5.0.24 / Chrome / Windows 11

**Comment by evilaliv3** [comment]
Thank you for reporting this @maelaborazioni 

We will check on this an implement proper block on the submission on the report and try to ship a fix with the next minor release.

**Comment by evilaliv3** [comment]
I think what we could do here is to verify that if the field is marked "mandatory" there should be at least a recording.

The check on the length is probably more difficult and not necessary because anyhow to save the recording the length requirement will need to be met before the user can save the file.

**Comment by evilaliv3** [comment]
@maelaborazioni : The fix to this issue has been included in current release 5.0.26.

thank you again for your feedback!

**Comment by evilaliv3** [comment]
Actually i had to rollback the work that we made to enforce mandatory checks on file uploads and voice questions.

I will re-open a new clean ticket to keep track of the need for fixing this aspects.
