### ISSUE TITLE
Docker Container on Dockerhub

### ISSUE THREAD

**Issue by cdftrew** [globaleaks/globaleaks-whistleblowing-software#4310]
### What version of GlobaLeaks are you using?

5.0.25

### What operating system(s) are you seeing the problem on?

Windows, Linux

### Describe the issue

I think the docker containers on dockerhub have not been updated correctly since version 5.0.18, when I install version 5.0.25 the admin gui shows version 5.0.18. When I manually download the images since 5.0.18, they are exactly the same.
![image](https://github.com/user-attachments/assets/c9cf9ddd-b39e-424e-ab22-213d294f2ec3)

**Comment by evilaliv3** [comment]
Thank you for notifying this @cdftrew 

I think the problem was due to the caching implemented in dockerhub, that was considering the layer cached and not fetching the latest packages.

We are now building a new image 5.0.26 where the new correct package seems is installed:
![Screenshot 2024-11-13 at 22-13-37 Image Layer Details - globaleaks_globaleaks v5 0 26 Docker Hub](https://github.com/user-attachments/assets/22ad2163-6840-4576-be59-62c9767768b8)
